drone_inventory/__init__.py
from logging import root
from flask import Flask, render_template, request, redirect
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_cors import CORS

from config import Config

from .site.routes import site
# from .api.routes import api

# from .templates.models import db, Patient



app = Flask(__name__)
app.register_blueprint(site)
# app.register_blueprint(api)


# app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///patients.db'
# app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
# db.init_app(app)

# @app.before_first_request
# def create_table():
#     db.create_all()

@app.route('/create' , methods = ['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('profile.html')

# app.run(host='localhost', port=5000)
# root_db.init_app(app)
# login_manager.init_app(app)
# login_manager.login_view = 'auth.signin' 
# # specify page rendered for non-authorized users ^
# ma.init_app(app)
# migrate = Migrate(app, root_db)

# CORS(app)
# app.json_encoder=JSONEncoder

drone_inventory/site/routes.py
from flask import Blueprint, render_template


site = Blueprint('site', __name__, template_folder='site_templates')

''' note that in the above code some arguments are specified 
the blueprint object the first argument sit is the blueprint's name'''

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>MedPro</title>
</head>
<body>
<!-- navbar -->
<nav class="ct-nav">
    <a href="{{ url_for('site.home') }}"><h1>MedPro</h1></a>
    
    <!-- Nav Items -->
    <div id="nav-list">
        <ul id="horizontal-list">
            <a href="{{ url_for('site.profile') }}"><li>Portal</li></a>

            <a href="">
                <li>Sign In with Google</li>
            </a>
            
        </ul>
    </div>

</nav>

<!-- end of navbar -->

{% block content %}
{% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>

</body>
</html>

drone_inventory/templates/forms.html
<!-- HTML produced by the UserLoginForm -->

<form  method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="facility-field">
            {{ form.facility.label }}
            {{ form.email(class = 'form-control', placeholder = 'Enter The Name of Your Facility...') }}
        </fieldset>
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'Enter email...') }}
        </fieldset>
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class = 'form-control', placeholder = 'Enter Password ...') }}
        </fieldset>
        <fieldset id="confirm-field">
            {{ form.confirm.label }}
            {{ form.confirm(class = 'form-control', placeholder = 'Confirm Password ...') }}
        </fieldset>

        {{ form.submit_button(class='btn btn-primary btn-block', id='sub-btn')  }}
    </div>
</form>